/**
 * Antigravity adapter.
 *
 * Antigravity consumes markdown agents/skills. We emit a markdown file with a
 * small metadata header and the prompt body. Fresh context on Antigravity is
 * delivered through Gemini search grounding, surfaced via the resolved tools.
 */
import type {
  GeneratedFile,
  ManualContext,
  PlatformAdapter,
  ResolvedAgent,
} from "./types.js";
import { launcherBody, withFrontmatter } from "./manual.js";

export const antigravityAdapter: PlatformAdapter = {
  id: "antigravity",
  displayName: "Antigravity",
  // Verified: Antigravity reads the .agents/ directory — Agent Skills in
  // .agents/skills/<name>/SKILL.md (agent-triggered) and Workflows in
  // .agents/workflows/<name>.md (manual /<name>). https://antigravity.google/docs/skills
  skillSupport: {
    verified: true,
    note: ".agents/skills/<cmd>/SKILL.md (decision-routed) + .agents/workflows/<cmd>.md (/<cmd>).",
  },
  render({ agent, model, tools }: ResolvedAgent): GeneratedFile {
    const header = [
      `# ${agent.name}`,
      "",
      `> ${agent.description.trim()}`,
      "",
      "| Field | Value |",
      "| --- | --- |",
      `| Model | ${model.effectiveTier === "inherit" ? "inherit" : model.model} |`,
      `| Tools | ${tools.join(", ")} |`,
      `| Trigger | ${agent.triggers.join(", ")} |`,
      "",
      "<!-- GENERATED by harness — edit .subagents/" +
        agent.name +
        ".yaml instead. -->",
      "",
      "## Instructions",
      "",
      agent.prompt.trim(),
    ].join("\n");

    return {
      relPath: `.antigravity/agents/${agent.name}.md`,
      contents: header + "\n",
    };
  },

  renderManual({ agent, command, wantsSkill, wantsCommand }: ManualContext): GeneratedFile[] {
    const files: GeneratedFile[] = [];
    if (wantsSkill) {
      files.push({
        relPath: `.agents/skills/${command}/SKILL.md`,
        contents: withFrontmatter(
          { name: command, description: agent.description.trim() },
          launcherBody(agent, "skill"),
        ),
      });
    }
    if (wantsCommand) {
      files.push({
        relPath: `.agents/workflows/${command}.md`,
        contents: withFrontmatter(
          { description: `Run the ${agent.name} workflow` },
          launcherBody(agent, "workflow"),
        ),
      });
    }
    return files;
  },
};
