/**
 * Antigravity adapter.
 *
 * Verified: Antigravity has no standalone sub-agent file — agents are expressed
 * as Agent Skills under .agents/skills/<name>/SKILL.md (plus AGENTS.md), and
 * sub-agent definitions live inside skills. So the sub-agent IS the skill here:
 * render() emits a full SKILL.md and renderManual emits only the manual
 * workflow. https://antigravity.google/docs/skills · /docs/subagents
 */
import type {
  GeneratedFile,
  ManualContext,
  PlatformAdapter,
  ResolvedAgent,
} from "./types.js";
import { launcherBody, withFrontmatter } from "./manual.js";

const agentRelPath = (name: string) => `.agents/skills/${name}/SKILL.md`;

export const antigravityAdapter: PlatformAdapter = {
  id: "antigravity",
  displayName: "Antigravity",
  agentRelPath,
  // The sub-agent (an Agent Skill) is itself the decision-routed surface.
  subagentIsSkill: true,
  skillSupport: {
    verified: true,
    note: "Sub-agent = Agent Skill (.agents/skills/<name>/SKILL.md); manual via .agents/workflows/<cmd>.md (/<cmd>).",
  },
  // The canonical Antigravity agent: a full Agent Skill with the real prompt.
  render({ agent }: ResolvedAgent): GeneratedFile {
    const body = [
      `<!-- GENERATED by harness from .subagents/${agent.name}.yaml — do not edit. -->`,
      "",
      agent.prompt.trim(),
    ].join("\n");
    return {
      relPath: agentRelPath(agent.name),
      contents: withFrontmatter(
        { name: agent.name, description: agent.description.trim() },
        body,
      ),
    };
  },

  // The skill surface is the agent itself (render); here we add only the manual
  // workflow when a command is requested.
  renderManual({ agent, command, wantsCommand }: ManualContext): GeneratedFile[] {
    if (!wantsCommand) return [];
    return [
      {
        relPath: `.agents/workflows/${command}.md`,
        contents: withFrontmatter(
          { description: `Run the ${agent.name} workflow` },
          launcherBody(agent, "workflow"),
        ),
      },
    ];
  },
};
