/**
 * Antigravity adapter.
 *
 * Antigravity consumes markdown agents/skills. We emit a markdown file with a
 * small metadata header and the prompt body. Fresh context on Antigravity is
 * delivered through Gemini search grounding, surfaced via the resolved tools.
 */
import type { GeneratedFile, PlatformAdapter, ResolvedAgent } from "./types.js";

export const antigravityAdapter: PlatformAdapter = {
  id: "antigravity",
  displayName: "Antigravity",
  render({ agent, model, tools }: ResolvedAgent): GeneratedFile {
    const header = [
      `# ${agent.name}`,
      "",
      `> ${agent.description.trim()}`,
      "",
      "| Field | Value |",
      "| --- | --- |",
      `| Model | ${model.effectiveTier === "inherit" ? "inherit" : model.model} |`,
      `| Tools | ${tools.join(", ")} |`,
      `| Trigger | ${agent.triggers.join(", ")} |`,
      "",
      "<!-- GENERATED by harness — edit .subagents/" +
        agent.name +
        ".yaml instead. -->",
      "",
      "## Instructions",
      "",
      agent.prompt.trim(),
    ].join("\n");

    return {
      relPath: `.antigravity/agents/${agent.name}.md`,
      contents: header + "\n",
    };
  },
};
