/**
 * Codex adapter.
 *
 * Verified: Codex custom sub-agents are TOML files in .codex/agents/<name>.toml
 * (name, description, developer_instructions, optional model / sandbox_mode);
 * https://developers.openai.com/codex/subagents. Skills are separate
 * (.agents/skills/, see renderManual).
 */
import type {
  GeneratedFile,
  ManualContext,
  PlatformAdapter,
  ResolvedAgent,
} from "./types.js";
import { launcherBody, withFrontmatter } from "./manual.js";

const agentRelPath = (name: string) => `.codex/agents/${name}.toml`;

/** TOML basic string (single line). */
function tomlStr(s: string): string {
  return `"${s.replace(/\\/g, "\\\\").replace(/"/g, '\\"')}"`;
}

/** TOML multi-line basic string; escapes backslashes and any embedded """. */
function tomlMulti(s: string): string {
  const escaped = s.replace(/\\/g, "\\\\").replace(/"""/g, '\\"\\"\\"');
  return `"""\n${escaped}\n"""`;
}

export const codexAdapter: PlatformAdapter = {
  id: "codex",
  displayName: "Codex",
  agentRelPath,
  // Verified: Codex Agent Skills live in .agents/skills/<name>/SKILL.md (scanned
  // up to the repo root). Implicit + explicit ($name) invocation, toggled by
  // allow_implicit_invocation. Custom prompts (~/.codex/prompts) are deprecated
  // and home-only, so the repo-shareable surface is the skill.
  // https://developers.openai.com/codex/skills
  skillSupport: {
    verified: true,
    note: ".agents/skills/<cmd>/SKILL.md — implicit when skill, explicit $<cmd> when command-only.",
  },
  render({ agent, model }: ResolvedAgent): GeneratedFile {
    const lines = [
      `# GENERATED by harness from .subagents/${agent.name}.yaml — do not edit.`,
      `name = ${tomlStr(agent.name)}`,
      `description = ${tomlMulti(agent.description.trim())}`,
    ];
    if (model.effectiveTier !== "inherit") {
      lines.push(`model = ${tomlStr(model.model)}`);
    }
    // No write capability → run the sub-agent read-only.
    if (!agent.capabilities.includes("write")) {
      lines.push(`sandbox_mode = ${tomlStr("read-only")}`);
    }
    lines.push(`developer_instructions = ${tomlMulti(agent.prompt.trim())}`);
    return {
      relPath: agentRelPath(agent.name),
      contents: lines.join("\n") + "\n",
    };
  },

  renderManual({ agent, command, wantsSkill }: ManualContext): GeneratedFile[] {
    // One Agent-Skill file serves both surfaces. When only a manual command is
    // wanted, disable implicit invocation so it runs only via explicit $<cmd>.
    const fm: Record<string, unknown> = {
      name: command,
      description: agent.description.trim(),
    };
    if (!wantsSkill) fm.allow_implicit_invocation = false;
    return [
      {
        relPath: `.agents/skills/${command}/SKILL.md`,
        contents: withFrontmatter(
          fm,
          launcherBody(agent, wantsSkill ? "skill" : "command"),
        ),
      },
    ];
  },
};
