/**
 * GitHub Copilot adapter.
 *
 * Copilot reads custom instructions/agents from `.github/`. We emit a markdown
 * agent file; the harness-init-agent confirms the exact placement/format
 * against current Copilot docs (formats drift).
 */
import type { GeneratedFile, PlatformAdapter, ResolvedAgent } from "./types.js";

export const copilotAdapter: PlatformAdapter = {
  id: "copilot",
  displayName: "GitHub Copilot",
  render({ agent, model, tools }: ResolvedAgent): GeneratedFile {
    const body = [
      `# ${agent.name}`,
      "",
      `> ${agent.description.trim()}`,
      "",
      "| Field | Value |",
      "| --- | --- |",
      `| Model | ${model.effectiveTier === "inherit" ? "host-managed" : model.model} |`,
      `| Tools | ${tools.join(", ")} |`,
      `| Trigger | ${agent.triggers.join(", ")} |`,
      "",
      `<!-- GENERATED by harness from .subagents/${agent.name}.yaml — do not edit. -->`,
      "",
      "## Instructions",
      "",
      agent.prompt.trim(),
    ].join("\n");
    return {
      relPath: `.github/copilot/agents/${agent.name}.md`,
      contents: body + "\n",
    };
  },
};
