/**
 * GitHub Copilot adapter.
 *
 * Verified: a Copilot custom agent IS the sub-agent — a Markdown file with YAML
 * frontmatter at .github/agents/<name>.agent.md (name, description, tools,
 * model), decision-routed/selectable. Manual invocation is a prompt file at
 * .github/prompts/<name>.prompt.md (/<name>).
 * https://code.visualstudio.com/docs/agent-customization/custom-agents
 */
import type {
  GeneratedFile,
  ManualContext,
  PlatformAdapter,
  ResolvedAgent,
} from "./types.js";
import { launcherBody, withFrontmatter } from "./manual.js";

const agentRelPath = (name: string) => `.github/agents/${name}.agent.md`;

export const copilotAdapter: PlatformAdapter = {
  id: "copilot",
  displayName: "GitHub Copilot",
  agentRelPath,
  // The custom agent is itself the decision-routed surface.
  subagentIsSkill: true,
  skillSupport: {
    verified: true,
    note: "Sub-agent = custom agent (.github/agents/<name>.agent.md); manual via .github/prompts/<cmd>.prompt.md (/<cmd>).",
  },
  // The canonical Copilot agent: a full custom agent with the real prompt.
  render({ agent, model, tools }: ResolvedAgent): GeneratedFile {
    const fm: Record<string, unknown> = {
      name: agent.name,
      description: agent.description.trim(),
      tools,
    };
    if (model.effectiveTier !== "inherit") fm.model = model.model;
    const body = [
      `<!-- GENERATED by harness from .subagents/${agent.name}.yaml — do not edit. -->`,
      "",
      agent.prompt.trim(),
    ].join("\n");
    return { relPath: agentRelPath(agent.name), contents: withFrontmatter(fm, body) };
  },

  // The skill surface is the custom agent itself (render); here we add only the
  // manual prompt-file command when requested.
  renderManual({ agent, command, wantsCommand }: ManualContext): GeneratedFile[] {
    if (!wantsCommand) return [];
    return [
      {
        relPath: `.github/prompts/${command}.prompt.md`,
        contents: withFrontmatter(
          { mode: "agent", description: `Run the ${agent.name} workflow` },
          launcherBody(agent, "command"),
        ),
      },
    ];
  },
};
