/**
 * Cursor adapter.
 *
 * Cursor consumes project rules/agents as Markdown. We emit a markdown agent
 * file with a metadata header; the harness-init-agent confirms the exact
 * placement/format against current Cursor docs (formats drift).
 */
import type { GeneratedFile, PlatformAdapter, ResolvedAgent } from "./types.js";

export const cursorAdapter: PlatformAdapter = {
  id: "cursor",
  displayName: "Cursor",
  skillSupport: {
    verified: false,
    note: "Cursor command/skill mechanism not yet mapped — the harness-init-agent confirms it via research.",
  },
  render({ agent, model, tools }: ResolvedAgent): GeneratedFile {
    const body = [
      `# ${agent.name}`,
      "",
      `> ${agent.description.trim()}`,
      "",
      "| Field | Value |",
      "| --- | --- |",
      `| Model | ${model.effectiveTier === "inherit" ? "host-managed" : model.model} |`,
      `| Tools | ${tools.join(", ")} |`,
      `| Trigger | ${agent.triggers.join(", ")} |`,
      "",
      `<!-- GENERATED by harness from .subagents/${agent.name}.yaml — do not edit. -->`,
      "",
      "## Instructions",
      "",
      agent.prompt.trim(),
    ].join("\n");
    return { relPath: `.cursor/agents/${agent.name}.md`, contents: body + "\n" };
  },
};
